blogproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    # 实际视图调用  detail(request, pk=244)
    path('posts/<int:pk>/', views.detail, name='detail'),
    # ｄｊａｎｇｏ会从用户访问打ＵＲＬ中自动提取ＵＲＬ路径参数转换器<type:name>规则捕获打值
    # 然后传递给其对应打视图函数．
    # archive视图函数打实际调用为：archive(request, year=2017, month=3)
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.category, name='category'),
    path('tags/<int:pk>', views.tag, name='tag'),

]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

blogproject/comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

blogproject/blog/models.py
import markdown
from django.utils.html import strip_tags

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标题', max_length=78)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')

    excerpt = models.CharField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)

    # step 10
    body = models.TextField()

    # step 20
    # 新增ｖｉｅｗｓ字段记录阅读量
    # PositiveIntegerField类型，该类型只允许为正整数或０，因为阅读量不可能为负值．
    # edutable为False表示，该字段不允许通过django admin后台编辑．
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        # ordering用来指定文章排序方式，
        # ['-created_time']　这里指定按照文章发布时间排序，负号表示逆序排列
        # 列表中可以有多个项　
        # ordering = ['-created_time', 'title']，表示首先依据时间排序，如果时间相同，则按照title排序
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    # 因为每次保存模型时，都需要修改modified_time打值，
    # 每一个Model都有一个save方法，这个方法包含了将model数据保存到数据库中打逻辑。、
    # 在指定完modified_time的值后，别忘记调用父类打save方法以执行数据保存回数据库打逻辑
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        # 首先实例化一个Markdown类，用于渲染body的文本
        # 由于摘要并不需要生成文章目录，所以去掉了目录扩展
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        # 先将Markdown文本渲染成HTML文本
        # strip_tags去掉HTML文本打全班HTML标签
        # 从文本中摘取前54个字符赋值给excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:54]

        super().save(*args, **kwargs)

    # 自定义方法
    # 从django.urls导入reverse方法
    def get_absolute_url(self):
        # blog:detail 意思就是blog应用下打name=detail的函数
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        # update_field告诉数据库只更新views字段
        self.save(update_fields=['views'])

blogproject/comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    # 一个评论只能属于一篇文章，一个篇文章可以有多个评论，是一对多打关系．
    # 因此这里使用的是ＦｏｒｅｉｇｎＫｅｙ

    # 所有模型的字段都接受一个verbose_name参数（大部分时第一个位置参数)，
    # django在根据模型打定义自动生成表单时，会使用这个参数的值作为表单字段打ｌａｂｅｌ，

    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blogproject/comments/forms.py
from django import forms
from .models import Comment


# 要使用django的表单功能，需要导入forms模块．
# django的表单类鼻息继承自forms.Form类或者form.ModelForm类．
class CommentForm(forms.ModelForm):
    class Meta:
        # 指定了这个表单对应打数据库模型Comment
        model = Comment
        # 指定了表单需要显示打字段
        fields = ['name', 'email', 'url', 'text']

blogproject/blog/views.py
import re
import markdown
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.shortcuts import render, HttpResponse, get_object_or_404


from .models import Post, Category, Tag
# Create your views here.

def index(request):
    # Post.objects.all()获取全部文章，而在归档和分类视图中，我们不再用ａｌｌ方法获取全部文章．
    #　而是使用ｆｉｌｔｅｒ来根基调剂过滤
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})
    # return render(request, 'blog/index.html', context={
    #     'title': 'my blog site',
    #     'welcome': 'welcome to my blog.'
    # })
    # return HttpResponse('Welcome to  this blog!@')


def archive(request, year, month):
    # python中调用属性的方式是通过created_time.year的方式调用，由于这里作为方法打参数列表，
    #　所以ｄｊａｎｇｏ要求ｗ我们把点替换成两个下划线，即created_time__year
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html',
                  context={'post_list': post_list})


def category(request, pk):
    # pk参数，就是被访问的分类的ｉｄ，
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')

    return render(request, 'blog/index.html', context={'post_list': post_list})


def tag(request, pk):
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-created_time')

    return render(request, 'blog/index.html', context={'post_list': post_list})

# 从URL中获取文章id（也就是pk，这里pk和id时等价打）获取数据库中文章id为该值的记录，
# 然后传递给模板
def detail(request, pk):
    # get_object_or_404 如果传入打pk存在时返回对应打post，如果不存在时，返回一个404 error
    post = get_object_or_404(Post, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 记得引入TocExtension 和 slugify
        TocExtension(slugify=slugify),
    ])

    # 阅读量 +1
    post.increase_views()

    # 使用convert方法将markdown文档转换成HTML文本，而一旦调用该方法md就会多出一个toc属性，
    # 这个属性的值就是内容打目录，然后把md.toc的值复制给post.toc
    # 然而post本身没有toc属性，但是可以动态添加这个属性，这就是python动态语言的好处
    post.body = md.convert(post.body)
    # post.toc = md.toc
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''

    return render(request, 'blog/detail.html', context={'post': post})

blogproject/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from django.views.decorators.http import require_POST
from django.contrib import messages

from .forms import CommentForm
# Create your views here.

# 装饰器require_POST 限定表单提交为POST请求
@require_POST
def comment(request, post_pk):
    # 先获取需要被评论打文章，然后将评论和文章关联起来
    # django提供打快捷函数get_object_or_404
    # 这个函数的作用是如果文章(Post )存在时，则获取；不存在，则返回404
    post = get_object_or_404(Post, pk=post_pk)
    # django将用户提交的数据封装在request.POST中，这是一个类字典对象
    # 我们利用这些数据构造一个CommentForm的实例，这样就生成了一个绑定了用户提交数据打表单
    form = CommentForm(request.POST)
    # 当调用is_valid()方法时，ｄｊａｎｇｏ会自动帮我们检查表单的数据是否符合格式要求
    if form.is_valid():
        # 检查数据合法，调用表单save方法保存数据到数据库
        # commit=False的作用仅仅是利用表单打数据生成一个Comment模型类的实例，但还不保存评论数据到数据库
        comment = form.save(commit=False)
        # 将评论和被评论的文章关联起来
        comment.post = post
        # 最终将评论数据保存进数据库，调用模型实例的save方法
        comment.save()
        # 重定向到ｐｏｓｔ的详情页，实际上当redirect函数接收一个模型的实例时，它会调用这个模型实例打get_absolute_url
        # 然后重定向到get_absolute_url方法返回的URL

        messages.add_message(request, messages.SUCCESS, '评论发表成功', extra_tags='success')
        return redirect(post)

    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误
    # 注意这里被评论打文章post也要传给模板，因为我们需要根基ｐｏｓｔ来生成表单的提交地址
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

blogproject/templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" re="stylesheet">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <style>
        .codehilite {
            padding: 0;
        }

        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-legt: 10px;
            white-space: pre;
        }
    </style>
</head>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<body id="single">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}

                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>
</html>

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <!--
                从index.html到评论区域需要跳转页面，因此　href 超链接指定为绝对URL,而文章详情和评论区在一个页面，因此只需要指定猫点即可
                -->
                <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body | safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        {% show_comment_form post %}
        <div class="comment-list-panel">
            {% show_comments post %}
        </div>
    </section>
{% endblock main %}
{% block toc %}
    {% if post.toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
            <div class="toc">
                <ul>
                    {{ post.toc|safe }}
                </ul>
            </div>
    </div>
    {% endif %}
 {% endblock toc %}

blogproject/templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
        <li>
           <!--a-- href="#">{{ date.year }} 年　{{ date.month }} 月</a-->
            <!--{ url }这个模板标签的作用时解析视图函数　blog:archive 对应的ＵＲＬ模式，
            并把ｕｒｌ模式中打年和月替换成date.year, date.month的值
            { url }模板标签接受的第一个参数为解析视图函数的端点值，这个端点值由２部分组成，
            中间由冒号分割．
            第一部分为在应用的urls.py中指定的app_name的值（充当命名空间，这样即使使用不同ａｐｐ下有相同打视图函数名，也不会冲突）
            第二部分path函数中传入打ｎａｍｅ参数的值

            比如：指定了app_name='blog', archive视图函数的url模式为
            path('archives/<int:year>/<int:month>', views.archive, name='archive')
            因此对应的端点值为blog:archive

            { url }模板标签接收打其他参数为ＵＲＬ路径参数，即ＵＲＬ模式中路径参数转换器需要捕获的值．
            比如：
                archive视图函数对应的url模式为archives/<int:year>/<int:month>/, 假设date.year=2017,
                date.month=5,
                那么{ url 'blog:archive' date.year date.month }模板标签返回的值为/archives/2017/5/

            为什么要使用{ url }模板标签呢？
            事实上把超链接的ｈｒｅｆ设置为/archives/{{ date.year }}/{{ date.month }}/同样卡亚达到目的，但这种写法是硬编码
            虽然现在　blog:archive视图函数对应打ＵＲＬ模式时这种形式，但是如果哪天这个模式改变了呢？
            如果使用了硬编码的写法，那你需要把每一处/archives/{{ date.year }}/{{ date.month }}/修改为新打模式，
            但是如果使用了{ url }模板标签，则不用做任何修改．

            -->
           <a href="{% url 'blog:archive' date.year date.month %}">
               {{ date.year }} 年　{{ date.month }} 月
           </a>
        </li>
        {% empty %}
        暂无归档
        {% endfor %}
    </ul>
</div>

blogproject/templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
        <li>
            <!--a href="#">{{ category.name }}<span class="post-count">(13)</span> </a-->
            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
        </li>
        {% empty %}
        暂无分类
        {% endfor %}
    </ul>
</div>

blogproject/templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
        暂无文章
        {% endfor %}
    </ul>
</div>

blogproject/templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {%for tag in tag_list %}
        <li>
            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
        </li>
        {% empty %}
        暂无标签
        {% endfor %}
    </ul>
</div>

blogproject/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}</p>
            <p>使用模板过滤器也可以实现摘要打效果 ---- truncatechars</p>
            <p>{{ post.excerpt|truncatechars:54 }}</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">no article posted</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock main %}

blogproject/templates/comments/inclusions/_form.html
<!--
form标签有两个重要的属性：　action　和　method
   action: 指定表单内容提交的地址
   method: 指定提交表单打ＨＴＴＰ请求类型，一般表单提交都是使用ＰＯＳＴ

   csrf_token: 这个模板标签在表单渲染时会自动渲染为一个隐藏类型打HTML　input控件，
   其值为一个随机字符串，作用主要是防护ＣＳＲＦ攻击(跨站请求伪造).

   comments_extras.py -> show_comment_form模板标签传递了一个模板变量form, 它是CommentForm的一个实例
   表单字段{{ form.name }}，{{ form.email }}，{{ form.url }}等将自动渲染成表单控件

   表单中并没有定义name, email, url等属性，那么他们是从哪里来的呢？
   CommentForm中Meta下的fields, django会自动将fields中声明的模型字段设置为表单打属性．

   {{ form.name.errors }}等将渲染表单对应字段的错误(如果有的话)，例如用户email格式错误等．
   django会自动检查用户提交打email格式．

   {{ form.xxx.label }}用来获取表单的label，django根据表单对应的模型中字段的verbose_name参数生成．
-->
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-from">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}: </label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}: </label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}: </label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}: </label>
            {{ form.text　}}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>
</form>

blogproject/templates/comments/inclusions/_list.html
<h3>评论列表, 共　<span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <time class="submit-date" datetime="{{ comment.created_time }}"></time>
            <div class="text">
                <!--linebreaks过滤器，浏览器会将换行以及多个空格合并为一个空格
                如果用户评论中有换行，浏览器会将换行替换成空格，从而显示打用户评论内容就会挤成一堆
                linebreaks过滤器预先将换行符替换为　br HTML标签，这样内容就能换行显示了．
                -->
                {{ comment.text|linebreaks }}
            </div>
        </li>
    {% empty %}
        暂无评论
    {% endfor %}
</ul>

blogproject/templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
    {% show_comment_form post form %}
{% endblock main %}